[server]
port = 8080
hostname = "https://my-podsync.onrender.com"

[storage]
  [storage.local]
  data_dir = "/app/data"

[tokens]
youtube = "AIzaSyB8KlRJZxB6Bj7Doq3l4FyVt1qq8qqHivs"

[feeds]
  [feeds.frmathew]
  url = "https://www.youtube.com/channel/UCsEfdsXejpne93addKoOhIw"
  page_size = 3
  update_period = "1h"
  quality = "high"
  format = "audio"
  clean = { keep_last = 2 }
