[server]
port = 8080
hostname = "https://my-podsync.onrender.com"

[storage]
  [storage.local]
  data_dir = "/app/data"

[tokens]
youtube = "AIzaSyDRjxawwTFSqAUwynUP3ZqLYiWEFvc-YLs"

[feeds]
  [feeds.frmathew]
  url = "https://www.youtube.com/channel/UCsEfdsXejpne93addKoOhIw"
  page_size = 2
  update_period = "1h"
  quality = "high"
  format = "audio"
  clean = { keep_last = 2 }
  youtube_dl_args = [
  "--extractor-args", "youtubepot-bgutilhttp:base_url=https://bgutil-ytdlp-pot-provider-latest-jzf2.onrender.com"
]
